name: UnutmaDostu
description: "M3 Code project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1  
  flutter_colorpicker: ^1.0.3
  table_calendar: ^3.1.1
  intl: ^0.19.0

  image_picker: ^1.1.1
  path_provider: ^2.0.5  
  csv: ^6.0.0
  modal_progress_hud_nsn: ^0.5.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  firebase_messaging: ^14.9.2
  firebase_auth : ^4.19.5
  google_sign_in: ^6.2.1
  awesome_dialog: ^3.2.1
  firebase_core: ^2.31.0
  path: ^1.8.0
  image: ^3.0.1
  connectivity_plus: ^3.0.3
  awesome_notifications: ^0.9.3+1
  
 

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images\Logo.png"
  
flutter:

  uses-material-design: true
  
  assets:
    - images/
    - images/door_sound.mp3
    - lib/datebase/output.csv